dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pycodestyle
script:
  - pycodestyle aee_parser.py
  - pylint aee_parser.py
  - pytest
